### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by bladyjoker** [mlabs-haskell/purescript-bridge#30]
TODO:
- [ ] Figure out how to RoundTrip test `purescript-bridge,nix` user type libraries
- [ ] Consider removing `plutus-ledger-api` typelib codegen alongside user typelibs and instead just link them with Nix
- [ ] Switch to using `psa` like CTL did and discuss with @ngua to consolidate Nix libs for purescript in a shared repo
- [ ] Refactor documentation and provide a `scaffold` example demonstrating the entire project setup
- [ ] Rename purescript-bridge to ctl-bridge
- [ ] Settle on the strategy for maintaining Cardano type codegeneration for CTL with ctl-bridge
- [ ] Deprecate nix/code-quality.nix and use https://github.com/cachix/pre-commit-hooks.nix
